// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  OffsetCoordinatesSmallMessage,
} from "./types";


export default __t.row({
  crumbTrailEntityId: __t.u64().name("crumb_trail_entity_id"),
  get exposedLocations() {
    return __t.array(OffsetCoordinatesSmallMessage).name("exposed_locations");
  },
  exposedHerdEntityId: __t.u64().name("exposed_herd_entity_id"),
});
