// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  ChatChannel,
  SurfaceType,
  Permission,
  PermissionGroup,
  SkillType,
  BuffCategory,
  ProgressiveActionStatus,
  AbilityTypeEnum,
} from "./types";


export default __t.row({
  placeholderId: __t.u64().primaryKey().name("placeholder_id"),
  get placeholderSkillType() {
    return SkillType.name("placeholder_skill_type");
  },
  get placeholderBuffCategory() {
    return BuffCategory.name("placeholder_buff_category");
  },
  get placeholder() {
    return ProgressiveActionStatus;
  },
  get placeholderWaterBodyType() {
    return SurfaceType.name("placeholder_water_body_type");
  },
  get chatChannel() {
    return ChatChannel.name("chat_channel");
  },
  get permission() {
    return Permission;
  },
  get permissionGroup() {
    return PermissionGroup.name("permission_group");
  },
  get abilityType() {
    return AbilityTypeEnum.name("ability_type");
  },
});
