export const MAP_WORLD_BOUNDS: Readonly<{ minX: number; minZ: number; maxX: number; maxZ: number }>;
export const MAP_MOBILE_SCALE: number;
export const MAP_DISPLAY_SCALE: number;
export const MAP_HEX_APOTHEM: number;
export type MapCoordinateInput = { x: number; z: number; dimension?: string | number | bigint };
export type MapCoordinatePoint = { x: number; z: number; dimension: string; coordinateSpace: "map-xz"; sourceCoordinateSpace?: "mobile-fixed-1000" };
export function normalizeStaticMapPoint(value: MapCoordinateInput): MapCoordinatePoint;
export function mapPointFromMobile(value: MapCoordinateInput): MapCoordinatePoint;
export function leafletPoint(value: Pick<MapCoordinateInput, "x" | "z">): [number, number];
export function displayHexPoint(value: Pick<MapCoordinateInput, "x" | "z">): { north: number; east: number };
