import type { AnyRecord } from "../main-app-data";
import type { ThemeSettings } from "../theme";
import type { ActivePanel } from "./app";

export type BrandingAsset = { fileName: string; contentType: string; updatedAt: string; url: string };
export type UserToastSettings = { marketListings: boolean; marketSales: boolean; production: boolean };
export type ActiveRegion = { regionId: string; regionName?: string; active?: boolean; syncing?: boolean; signedInPlayers?: number; playersInQueue?: number; updatedAt?: string | null; source?: string };
export type AppUser = {
  id: number;
  discordId: string;
  username: string;
  globalName: string;
  avatarUrl: string | null;
  characterPlayerId: string;
  characterName: string;
  characterStatus: "unlinked" | "pending" | "approved" | "rejected" | string;
  settings: AnyRecord;
  createdAt?: string;
  lastLoginAt?: string;
};
export type UserAuthState = { user: AppUser | null; discordLoginEnabled: boolean };
export type ColourRoleDefinition = { key: string; label: string; roleName: string; roleId: string; color: number };
export type DiscordRoleOption = { key: string; label: string; roleId: string; emoji: string };
export type DiscordRolePanel = { key: string; label: string; channelId: string; messageId: string; title: string; description: string; mode: "single" | "multi"; showHelperText: boolean; options: DiscordRoleOption[] };
export type DiscordWelcomeFlow = { enabled: boolean; channelId: string; messageId: string; title: string; message: string; readyRoleId: string; showNextStep: boolean };
export type DiscordPresence = { enabled: boolean; status: "online" | "idle" | "dnd" | "invisible"; activityType: "playing" | "watching" | "listening" | "competing"; activityText: string };
export type DiscordSettings = {
  enabled: boolean;
  applicationId: string;
  publicKey: string;
  guildId: string;
  channelId: string;
  minSaleValue: number;
  supplyRunwayDaysThreshold: number;
  productionMinXp: number;
  productionMinAgeMinutes: number;
  productionUsers: string;
  supplyReportIntervalDays: number;
  channels: Record<string, string>;
  notificationChannels: Record<string, string>;
  craftChannels: Record<string, string>;
  craftRoles: Record<string, string>;
  colourRolesChannelId: string;
  colourRolesMessageId: string;
  colourRoles: ColourRoleDefinition[];
  rolePanels: DiscordRolePanel[];
  welcomeFlow: DiscordWelcomeFlow;
  presence: DiscordPresence;
  notify: { marketListings: boolean; marketSales: boolean; production: boolean; productionStarted: boolean; productionCompleted: boolean; lowSupplies: boolean; appUpdates: boolean; supplyReports: boolean };
  botToken?: string;
  clearBotToken?: boolean;
  botTokenConfigured?: boolean;
  botTokenSource?: string | null;
  interactionUrl?: string;
};
export type AppSettings = {
  claimId: string;
  syncUrl: string;
  excludedMemberIds: string[];
  theme: ThemeSettings;
  refreshSeconds: number;
  serverRefreshSeconds: number;
  collectorSettings: Record<string, { label: string; enabled: boolean; intervalSeconds: number }>;
  defaultPage: ActivePanel;
  defaultRegion: string;
  additionalActiveRegions: string;
  toastSettings: { marketListings: boolean; marketSales: boolean; production: boolean };
  branding: { logo?: BrandingAsset; favicon?: BrandingAsset };
  snapshotRetentionDays: number;
  visitorSecurity: { fullIpRetentionDays: number; statsRetentionDays: number; geoipProvider: string; geoipCacheDays: number; geoipSourceUrl: string; geoipAccountId: string; geoipLicenseKey?: string; geoipLicenseKeyConfigured?: boolean; geoipClearLicenseKey?: boolean };
  browserSnapshotsEnabled: boolean;
  discord: DiscordSettings;
};
