// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  SmallHexTileMessage,
} from "./types";


export default __t.row({
  buildingEntityId: __t.u64().primaryKey().name("building_entity_id"),
  claimEntityId: __t.u64().name("claim_entity_id"),
  get coordinates() {
    return SmallHexTileMessage;
  },
});
