// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  EquipmentSlot,
} from "./types";


export default __t.row({
  entityId: __t.u64().primaryKey().name("entity_id"),
  playerEntityId: __t.u64().name("player_entity_id"),
  index: __t.i32(),
  active: __t.bool(),
  get equipmentSlots() {
    return __t.array(EquipmentSlot).name("equipment_slots");
  },
});
