// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  Rarity,
} from "./types";


export default __t.row({
  id: __t.i32().primaryKey(),
  name: __t.string(),
  tag: __t.string(),
  tier: __t.i32(),
  description: __t.string(),
  get rarity() {
    return Rarity;
  },
  modelAssetName: __t.string().name("model_asset_name"),
  iconAssetName: __t.string().name("icon_asset_name"),
  maxHealth: __t.i32().name("max_health"),
  visibleToOthers: __t.bool().name("visible_to_others"),
  spawnsOnLand: __t.bool().name("spawns_on_land"),
  landElevationMin: __t.i32().name("land_elevation_min"),
  landElevationMax: __t.i32().name("land_elevation_max"),
  spawnsInWater: __t.bool().name("spawns_in_water"),
  waterDepthMin: __t.i32().name("water_depth_min"),
  waterDepthMax: __t.i32().name("water_depth_max"),
});
