// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  LevelRequirement,
  ItemStack,
  ToolRequirement,
  Biome,
  PlaceableSelfBuffChance,
} from "./types";


export default __t.row({
  id: __t.i32().primaryKey(),
  placedPlaceableId: __t.i32().name("placed_placeable_id"),
  get inputItem() {
    return ItemStack.name("input_item");
  },
  requiredTime: __t.f32().name("required_time"),
  get levelRequirements() {
    return __t.array(LevelRequirement).name("level_requirements");
  },
  get toolRequirements() {
    return __t.array(ToolRequirement).name("tool_requirements");
  },
  requiredKnowledges: __t.array(__t.i32()).name("required_knowledges"),
  blockingKnowledges: __t.array(__t.i32()).name("blocking_knowledges"),
  get requiredBiomes() {
    return __t.array(Biome).name("required_biomes");
  },
  placeOnLand: __t.bool().name("place_on_land"),
  landElevationMin: __t.i32().name("land_elevation_min"),
  landElevationMax: __t.i32().name("land_elevation_max"),
  placeOnWater: __t.bool().name("place_on_water"),
  waterDepthMin: __t.i32().name("water_depth_min"),
  waterDepthMax: __t.i32().name("water_depth_max"),
  requiredPavingTier: __t.i32().name("required_paving_tier"),
  requiredInteriorTier: __t.i32().name("required_interior_tier"),
  requiredClaimTier: __t.i32().name("required_claim_tier"),
  minDistanceToPlayerClaims: __t.i32().name("min_distance_to_player_claims"),
  minDistanceToGroup: __t.i32().name("min_distance_to_group"),
  minDistanceToOtherPlaceables: __t.i32().name("min_distance_to_other_placeables"),
  minDistanceToExistingFootprints: __t.i32().name("min_distance_to_existing_footprints"),
  maxDistanceToBuildings: __t.i32().name("max_distance_to_buildings"),
  buildings: __t.array(__t.i32()),
  recipePerformanceId: __t.i32().name("recipe_performance_id"),
  get selfBuffs() {
    return __t.option(__t.array(PlaceableSelfBuffChance)).name("self_buffs");
  },
});
