// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  ProbabilisticItemStack,
} from "./types";


export default __t.row({
  id: __t.i32().primaryKey(),
  extractionId: __t.i32().name("extraction_id"),
  enemyId: __t.i32().name("enemy_id"),
  itemListId: __t.i32().name("item_list_id"),
  requiredQuestId: __t.i32().name("required_quest_id"),
  requiredStageId: __t.i32().name("required_stage_id"),
  get itemDrop() {
    return ProbabilisticItemStack.name("item_drop");
  },
});
