// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  ItemStack,
  ExperienceStackF32,
  CappedLevelRequirement,
} from "./types";


export default __t.row({
  id: __t.i32().primaryKey(),
  get levelRequirement() {
    return CappedLevelRequirement.name("level_requirement");
  },
  get requiredItems() {
    return __t.array(ItemStack).name("required_items");
  },
  get rewardedItems() {
    return __t.array(ItemStack).name("rewarded_items");
  },
  get rewardedExperience() {
    return ExperienceStackF32.name("rewarded_experience");
  },
  description: __t.string(),
});
