// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  travelerTaskId: __t.i32().primaryKey().name("traveler_task_id"),
  requiredKnowledges: __t.array(__t.i32()).name("required_knowledges"),
  blockingKnowledges: __t.array(__t.i32()).name("blocking_knowledges"),
});
