import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

test("terrain is pre-generated by default and live rebuilding requires an explicit maintenance flag", async () => {
  const server = await readFile(new URL("../server.mjs", import.meta.url), "utf8");
  assert.match(server, /ENABLE_RELAY_TERRAIN_LIVE_REBUILD === "true"/);
  assert.match(server, /if \(terrainLiveRebuildEnabled\)/);
});

test("pre-generated terrain and road jobs have conservative default freshness gates", async () => {
  const terrain = await readFile(new URL("../scripts/build-relay-terrain-overview.mjs", import.meta.url), "utf8");
  const roads = await readFile(new URL("../scripts/verify-relay-roads-live.mjs", import.meta.url), "utf8");
  assert.match(terrain, /7 \* 24 \* 60 \* 60_000/);
  assert.match(roads, /24 \* 60 \* 60_000/);
  assert.match(terrain, /BITCRAFT_FORCE_TERRAIN_OVERVIEW/);
  assert.match(roads, /BITCRAFT_FORCE_ROAD_TILES/);
});
