import assert from "node:assert/strict";
import { existsSync, readFileSync, readdirSync } from "node:fs";
import test from "node:test";

const rootUrl = new URL("../../../", import.meta.url);
const readRoot = (path) => readFileSync(new URL(path, rootUrl), "utf8");

const currentDocs = [
  ".env.example",
  "README.md",
  "docs/application-overview.md",
  "docs/developer-guide.md",
];

const readSourceTree = (path) => {
  const url = new URL(path, rootUrl);
  return readdirSync(url, { recursive: true, withFileTypes: true })
    .filter((entry) => entry.isFile())
    .filter((entry) => /\.(?:mjs|ts|tsx|js|jsx)$/.test(entry.name))
    .map((entry) => readFileSync(`${entry.parentPath}/${entry.name}`, "utf8"))
    .join("\n");
};

test("current documentation and environment use only the Relay browser contract", () => {
  for (const path of currentDocs) {
    const contents = readRoot(path);
    assert.doesNotMatch(contents, /BITJITA_[A-Z_]+/);
    assert.doesNotMatch(contents, /\/api\/bitjita/i);
    assert.match(contents, /19430/);
  }

  const environment = readRoot(".env.example");
  assert.match(environment, /BITCRAFT_RELAY_ORIGIN=https:\/\/relay\.bitcraftsync\.app/);
  assert.match(environment, /DISCORD_DELIVERY_MODE=record/);
  assert.match(environment, /DISCORD_SANDBOX_CHANNEL_ID=/);

  const architecture = `${readRoot("README.md")}\n${readRoot("docs/application-overview.md")}`;
  assert.match(architecture, /\/api\/local\/game-data/);
  assert.match(architecture, /provider generation/i);
  assert.match(architecture, /last-good/i);
  assert.match(architecture, /DirectBitCraftProvider/);
  assert.match(architecture, /relay\.timbersteeltrade\.com/);

  const deploymentDocs = `${readRoot("README.md")}\n${readRoot("docs/developer-guide.md")}`;
  for (const expected of [
    "19428",
    "/opt/bitcraft-claim-monitor-relay",
    "/var/lib/bitcraft-claim-monitor-relay",
    "/var/backups/bitcraft-claim-monitor-relay",
    "/etc/bitcraft-claim-monitor-relay.env",
    "/usr/local/bin/update-bitcraft-claim-monitor-relay",
    "bitcraft-claim-monitor-relay.service",
  ]) {
    assert.match(deploymentDocs, new RegExp(expected.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")));
  }
  assert.doesNotMatch(deploymentDocs, /\b184(?:28|30)\b/);
});

test("dead generated upstream clients cannot be regenerated by this workspace", () => {
  for (const path of [
    "lib/api-spec",
    "lib/api-client-react",
    "lib/api-zod",
    "BITJITA_API_AUDIT.md",
  ]) {
    assert.equal(existsSync(new URL(path, rootUrl)), false, `${path} should be retired`);
  }

  const rootTsconfig = readRoot("tsconfig.json");
  assert.doesNotMatch(rootTsconfig, /api-client-react|api-zod|api-spec/);
  const lockfile = readRoot("pnpm-lock.yaml");
  assert.doesNotMatch(lockfile, /^\s{2}lib\/(?:api-spec|api-client-react|api-zod):/m);
});

test("icon source URLs remain immutable build-time provenance, never a runtime source", () => {
  const manifest = readRoot("apps/bitcraft-local/assets/game-icons-manifest.json");
  assert.match(manifest, /"originalUrl":\s*"https:\/\/bitjita\.com\//);

  const currentDocsText = currentDocs.map(readRoot).join("\n");
  assert.match(currentDocsText, /build-time provenance/i);
  assert.match(currentDocsText, /never fetched at runtime/i);

  const runtimeSources = [
    readSourceTree("apps/bitcraft-local/src/"),
    readRoot("apps/bitcraft-local/server.mjs"),
    readRoot("apps/bitcraft-local/vite.config.ts"),
  ].join("\n");
  assert.doesNotMatch(runtimeSources, /https:\/\/bitjita\.com/i);
});
