import assert from "node:assert/strict";
import { existsSync, readFileSync, readdirSync } from "node:fs";
import { relative } from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";

const rootUrl = new URL("../../../", import.meta.url);
const readRoot = (path) => readFileSync(new URL(path, rootUrl), "utf8");

const currentDocs = [
  ".env.example",
  "README.md",
  "docs/application-overview.md",
  "docs/developer-guide.md",
];

const sourceFiles = (path) => {
  const url = new URL(path, rootUrl);
  const basePath = fileURLToPath(url);
  return readdirSync(url, { recursive: true, withFileTypes: true })
    .filter((entry) => entry.isFile())
    .filter((entry) => /\.(?:mjs|ts|tsx|js|jsx)$/.test(entry.name))
    .map((entry) => ({
      path: `${path}${relative(basePath, entry.parentPath).replaceAll("\\", "/")}${entry.parentPath === basePath ? "" : "/"}${entry.name}`,
      contents: readFileSync(`${entry.parentPath}/${entry.name}`, "utf8"),
    }));
};

test("current documentation and environment use only the Relay browser contract", () => {
  for (const path of currentDocs) {
    const contents = readRoot(path);
    assert.doesNotMatch(contents, /BITJITA_[A-Z_]+/);
    assert.doesNotMatch(contents, /\/api\/bitjita/i);
    assert.match(contents, /19430/);
  }

  const environment = readRoot(".env.example");
  assert.match(environment, /BITCRAFT_RELAY_ORIGIN=https:\/\/relay\.bitcraftsync\.app/);
  assert.match(environment, /DISCORD_DELIVERY_MODE=record/);
  assert.match(environment, /DISCORD_SANDBOX_CHANNEL_ID=/);
  assert.match(environment, /manual.*test.*sandbox/i);
  assert.doesNotMatch(environment, /reserved for a later|later manual-delivery implementation/i);

  const architecture = `${readRoot("README.md")}\n${readRoot("docs/application-overview.md")}`;
  assert.match(architecture, /\/api\/local\/game-data/);
  assert.match(architecture, /provider generation/i);
  assert.match(architecture, /last-good/i);
  assert.match(architecture, /RelayBitCraftProvider/);
  assert.match(architecture, /relay\.timbersteeltrade\.com/);

  const deploymentDocs = `${readRoot("README.md")}\n${readRoot("docs/developer-guide.md")}`;
  assert.match(deploymentDocs, /manual.*test.*sandbox Discord channel/i);
  assert.match(deploymentDocs, /automatic.*record/i);
  for (const expected of [
    "19428",
    "/opt/bitcraft-claim-monitor-relay",
    "/var/lib/bitcraft-claim-monitor-relay",
    "/var/backups/bitcraft-claim-monitor-relay",
    "/etc/bitcraft-claim-monitor-relay.env",
    "/usr/local/bin/update-bitcraft-claim-monitor-relay",
    "bitcraft-claim-monitor-relay.service",
  ]) {
    assert.match(deploymentDocs, new RegExp(expected.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")));
  }
  assert.doesNotMatch(deploymentDocs, /\b184(?:28|30)\b/);
});

test("dead generated upstream clients cannot be regenerated by this workspace", () => {
  for (const path of [
    "lib/api-spec",
    "lib/api-client-react",
    "lib/api-zod",
    "BITJITA_API_AUDIT.md",
  ]) {
    assert.equal(existsSync(new URL(path, rootUrl)), false, `${path} should be retired`);
  }

  const rootTsconfig = readRoot("tsconfig.json");
  assert.doesNotMatch(rootTsconfig, /api-client-react|api-zod|api-spec/);
  const lockfile = readRoot("pnpm-lock.yaml");
  assert.doesNotMatch(lockfile, /^\s{2}lib\/(?:api-spec|api-client-react|api-zod):/m);
});

test("only the audited same-origin icon fallback may contact the approved BitJita origin", () => {
  const manifest = readRoot("apps/bitcraft-local/assets/game-icons-manifest.json");
  assert.match(manifest, /"originalUrl":\s*"https:\/\/bitjita\.com\//);

  const currentDocsText = currentDocs.map(readRoot).join("\n");
  assert.match(currentDocsText, /build-time provenance/i);
  assert.match(currentDocsText, /\/api\/local\/game-icon/);

  const server = readRoot("apps/bitcraft-local/server.mjs");
  const fallback = readRoot("apps/bitcraft-local/src/server/gameIconFallback.mjs");
  const approvedServerOrigin = 'metadataOrigin: process.env.BITJITA_ICON_API_ORIGIN ?? "https://bitjita.com",';
  const approvedServerHosts = 'approvedHosts: String(process.env.BITJITA_ICON_APPROVED_HOSTS ?? "bitjita.com,cdn.bitjita.com").split(","),';
  const approvedFallbackOrigin = 'const metadataOrigin = String(options.metadataOrigin ?? "https://bitjita.com").replace(/\\/+$/, "");';
  const approvedFallbackHosts = 'const approvedHosts = new Set((options.approvedHosts ?? ["bitjita.com", "cdn.bitjita.com"])';
  assert.equal(server.split(approvedServerOrigin).length - 1, 1);
  assert.equal(server.split(approvedServerHosts).length - 1, 1);
  assert.equal(fallback.split(approvedFallbackOrigin).length - 1, 1);
  assert.equal(fallback.split(approvedFallbackHosts).length - 1, 1);
  assert.doesNotMatch(server.replace(approvedServerOrigin, "").replace(approvedServerHosts, ""), /bitjita\.com/i);
  assert.doesNotMatch(fallback.replace(approvedFallbackOrigin, "").replace(approvedFallbackHosts, ""), /bitjita\.com/i);

  const unapprovedRuntimeSources = [
    ...sourceFiles("apps/bitcraft-local/src/").filter(({ path }) => path !== "apps/bitcraft-local/src/server/gameIconFallback.mjs"),
    { path: "apps/bitcraft-local/vite.config.ts", contents: readRoot("apps/bitcraft-local/vite.config.ts") },
  ].map(({ contents }) => contents).join("\n");
  assert.doesNotMatch(unapprovedRuntimeSources, /bitjita\.com/i);
});
