import assert from "node:assert/strict";
import test from "node:test";

let projectionModule = null;
try {
  projectionModule = await import(
    new URL("../src/server/game-data/researchProjection.ts", import.meta.url).href,
  );
} catch {
  // The first TDD run proves the research projection is absent.
}

test("research projection classifies learned, current, available, and locked technologies", () => {
  assert.ok(projectionModule, "research projection module must exist");
  const result = projectionModule.enrichResearchWithCatalog({
    claimId: "1369094286777412590",
    learnedTechIds: ["1", "200"],
    researchingTechId: "300",
    researchStartedAt: "2026-07-30T22:00:00.123Z",
    scheduledId: "9007199254740993",
  }, [{
    kind: "claim_tech",
    id: "1",
    name: "Claim Upgrades",
    description: "",
    tier: 0,
    techType: "Undefined",
    suppliesCost: "0",
    researchTime: "0",
    requirements: [],
    inputs: [],
    members: "50",
    area: "1000",
    supplies: "12000",
    xpToMintHexCoin: "400",
    unlocksTechs: [],
  }, {
    kind: "claim_tech",
    id: "200",
    name: "Tier 2",
    description: "Unlocks tier 2 research.",
    tier: 2,
    techType: "TierUpgrade",
    suppliesCost: "10",
    researchTime: "0",
    requirements: [],
    inputs: [],
    members: "0",
    area: "0",
    supplies: "0",
    xpToMintHexCoin: "400",
    unlocksTechs: [],
  }, {
    kind: "claim_tech",
    id: "300",
    name: "Tier 3",
    description: "Unlocks tier 3 research.",
    tier: 3,
    techType: "TierUpgrade",
    suppliesCost: "1500",
    researchTime: "0",
    requirements: ["200"],
    inputs: [],
    members: "0",
    area: "0",
    supplies: "0",
    xpToMintHexCoin: "400",
    unlocksTechs: [],
  }, {
    kind: "claim_tech",
    id: "400",
    name: "Tier 4",
    description: "Unlocks tier 4 research.",
    tier: 4,
    techType: "TierUpgrade",
    suppliesCost: "2250",
    researchTime: "0",
    requirements: ["300"],
    inputs: [],
    members: "0",
    area: "0",
    supplies: "0",
    xpToMintHexCoin: "400",
    unlocksTechs: [],
  }, {
    kind: "claim_tech",
    id: "748616905",
    name: "Town Bank",
    description: "Unlocks a town bank.",
    tier: 2,
    techType: "TownBank",
    suppliesCost: "500",
    researchTime: "0",
    requirements: ["200"],
    inputs: [],
    members: "0",
    area: "0",
    supplies: "0",
    xpToMintHexCoin: "0",
    unlocksTechs: [],
  }]);

  assert.deepEqual(result, {
    data: {
      claimId: "1369094286777412590",
      learnedTechIds: ["1", "200"],
      researchingTechId: "300",
      researchStartedAt: "2026-07-30T22:00:00.123Z",
      scheduledId: "9007199254740993",
      technologies: [
        {
          kind: "claim_tech",
          id: "1",
          entityId: "1",
          name: "Claim Upgrades",
          description: "",
          tier: 0,
          techType: "Undefined",
          suppliesCost: "0",
          researchTime: "0",
          requirements: [],
          inputs: [],
          members: "50",
          area: "1000",
          supplies: "12000",
          xpToMintHexCoin: "400",
          unlocksTechs: [],
          state: "researched",
          isResearched: true,
          isResearching: false,
          isAvailable: false,
          missingRequirementIds: [],
        },
        {
          kind: "claim_tech",
          id: "200",
          entityId: "200",
          name: "Tier 2",
          description: "Unlocks tier 2 research.",
          tier: 2,
          techType: "TierUpgrade",
          suppliesCost: "10",
          researchTime: "0",
          requirements: [],
          inputs: [],
          members: "0",
          area: "0",
          supplies: "0",
          xpToMintHexCoin: "400",
          unlocksTechs: [],
          state: "researched",
          isResearched: true,
          isResearching: false,
          isAvailable: false,
          missingRequirementIds: [],
        },
        {
          kind: "claim_tech",
          id: "300",
          entityId: "300",
          name: "Tier 3",
          description: "Unlocks tier 3 research.",
          tier: 3,
          techType: "TierUpgrade",
          suppliesCost: "1500",
          researchTime: "0",
          requirements: ["200"],
          inputs: [],
          members: "0",
          area: "0",
          supplies: "0",
          xpToMintHexCoin: "400",
          unlocksTechs: [],
          state: "researching",
          isResearched: false,
          isResearching: true,
          isAvailable: false,
          missingRequirementIds: [],
          researchStartedAt: "2026-07-30T22:00:00.123Z",
          scheduledId: "9007199254740993",
        },
        {
          kind: "claim_tech",
          id: "400",
          entityId: "400",
          name: "Tier 4",
          description: "Unlocks tier 4 research.",
          tier: 4,
          techType: "TierUpgrade",
          suppliesCost: "2250",
          researchTime: "0",
          requirements: ["300"],
          inputs: [],
          members: "0",
          area: "0",
          supplies: "0",
          xpToMintHexCoin: "400",
          unlocksTechs: [],
          state: "locked",
          isResearched: false,
          isResearching: false,
          isAvailable: false,
          missingRequirementIds: ["300"],
        },
        {
          kind: "claim_tech",
          id: "748616905",
          entityId: "748616905",
          name: "Town Bank",
          description: "Unlocks a town bank.",
          tier: 2,
          techType: "TownBank",
          suppliesCost: "500",
          researchTime: "0",
          requirements: ["200"],
          inputs: [],
          members: "0",
          area: "0",
          supplies: "0",
          xpToMintHexCoin: "0",
          unlocksTechs: [],
          state: "available",
          isResearched: false,
          isResearching: false,
          isAvailable: true,
          missingRequirementIds: [],
        },
      ],
    },
    warnings: [],
  });
});

test("research projection reports state IDs missing from the global catalog", () => {
  assert.ok(projectionModule, "research projection module must exist");
  const result = projectionModule.enrichResearchWithCatalog({
    claimId: "42",
    learnedTechIds: ["1", "999"],
    researchingTechId: "888",
    researchStartedAt: null,
    scheduledId: null,
  }, [{
    kind: "claim_tech",
    id: "1",
    name: "Claim Upgrades",
    requirements: [],
  }]);

  assert.deepEqual(result.warnings, [
    "Research state references learned technology 999 missing from the global catalog.",
    "Research state references current technology 888 missing from the global catalog.",
  ]);
  assert.equal(result.data.technologies.length, 1);
});
